# Data Source
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot
    username: root
    password: root1234
    driverClassName: com.mysql.cj.jdbc.Driver
      
# JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    show-sql: true
  